# -*- coding: utf-8 -*-
"""IMPLEMENTED_RECRUITMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-5wl9iIq1aA-m7Ap8lGzt7lizjsAt1-
"""

!pip -q install pymupdf
!pip -q install python-docx
!pip -q install sentence-transformers
!pip -q install spacy
!pip -q install scikit-learn
!pip -q install shap
!pip -q install plotly
!pip -q install fpdf2

!python -m spacy download en_core_web_sm

import os
import re
import json

import numpy as np
import pandas as pd

import fitz

from docx import Document

from google.colab import files

import spacy

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

import shap


import matplotlib.pyplot as plt
import plotly.express as px

from IPython.display import display

nlp = spacy.load("en_core_web_sm")

print("✅ All libraries loaded successfully.")

print("Upload ONE Job Description (PDF or DOCX)")

uploaded_job = files.upload()

print("Upload one or more Candidate Resumes")

uploaded_resumes = files.upload()

import fitz
from docx import Document
import os
import pandas as pd



def extract_text_from_pdf(file_path):
    """
    Extract text from a PDF resume.
    """
    text = ""

    pdf = fitz.open(file_path)

    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text



def extract_text_from_docx(file_path):
    """
    Extract text from a DOCX resume.
    """
    doc = Document(file_path)

    text = ""

    for paragraph in doc.paragraphs:
        text += paragraph.text + "\n"

    return text



resume_records = []

for file_name in uploaded_resumes.keys():

    print(f"Parsing : {file_name}")

    if file_name.lower().endswith(".pdf"):

        resume_text = extract_text_from_pdf(file_name)

    elif file_name.lower().endswith(".docx"):

        resume_text = extract_text_from_docx(file_name)

    else:

        print("Unsupported File")

        continue

    resume_records.append({

        "Resume_File": file_name,
        "Resume_Text": resume_text

    })

print("\nResume Parsing Completed.")

resume_df = pd.DataFrame(resume_records)

print("Total Resumes Parsed :", len(resume_df))

display(resume_df.head())

candidate_number = 0

print("Resume File:")
print(resume_df.loc[candidate_number, "Resume_File"])

print("\n")

print("Resume Text:\n")

print(resume_df.loc[candidate_number, "Resume_Text"])

candidate_number = 1

print("Resume File:")
print(resume_df.loc[candidate_number, "Resume_File"])

print("\n")

print("Resume Text:\n")

print(resume_df.loc[candidate_number, "Resume_Text"])

import re
import pandas as pd



def extract_email(text):

    pattern = r'[\w\.-]+@[\w\.-]+\.\w+'

    match = re.search(pattern, text)

    if match:
        return match.group()

    return "Not Found"



def extract_phone(text):

    pattern = r'(\+?\d[\d\s\-\(\)]{8,}\d)'

    match = re.search(pattern, text)

    if match:
        return match.group().strip()

    return "Not Found"



def extract_linkedin(text):

    pattern = r'(https?://)?(www\.)?linkedin\.com/in/[A-Za-z0-9\-_]+'

    match = re.search(pattern, text)

    if match:
        return match.group()

    return "Not Found"




def extract_name(text):

    lines = text.split("\n")

    for line in lines:

        line = line.strip()

        if len(line) > 2:

            if "@" not in line and "linkedin" not in line.lower():

                return line

    return "Not Found"

resume_df["Candidate_Name"] = resume_df["Resume_Text"].apply(extract_name)

resume_df["Email"] = resume_df["Resume_Text"].apply(extract_email)

resume_df["Phone"] = resume_df["Resume_Text"].apply(extract_phone)

resume_df["LinkedIn"] = resume_df["Resume_Text"].apply(extract_linkedin)

print("Basic Information Extracted Successfully.")

resume_df[
    [
        "Candidate_Name",
        "Email",
        "Phone",
        "LinkedIn",
        "Resume_File"
    ]
]

skills = [
    "Python",
    "Java",
    "SQL",
    "Docker",
    ...
]

import fitz
from docx import Document


def read_pdf(file_name):

    text = ""

    pdf = fitz.open(file_name)

    for page in pdf:

        text += page.get_text()

    pdf.close()

    return text



def read_docx(file_name):

    doc = Document(file_name)

    text = ""

    for paragraph in doc.paragraphs:

        text += paragraph.text + "\n"

    return text



job_filename = list(uploaded_job.keys())[0]

print("Reading :", job_filename)

if job_filename.endswith(".pdf"):

    job_description_text = read_pdf(job_filename)

elif job_filename.endswith(".docx"):

    job_description_text = read_docx(job_filename)

else:

    raise ValueError("Unsupported File Format")

print("Job Description Loaded Successfully.")

!pip install -q PyMuPDF

import fitz

print("PyMuPDF Installed Successfully!")

!pip -q install --upgrade pip

!pip -q install pandas
!pip -q install numpy

!pip -q install PyMuPDF
!pip -q install python-docx

!pip -q install spacy

!pip -q install sentence-transformers

!pip -q install scikit-learn

!pip -q install shap

!pip -q install plotly
!pip -q install matplotlib

!pip -q install fpdf2

!python -m spacy download en_core_web_sm

print("✅ Environment Installed Successfully")

import fitz
import pandas as pd
import numpy as np
import spacy
import shap

from docx import Document
from sentence_transformers import SentenceTransformer

print("✅ PyMuPDF :", fitz.__doc__[:25])
print("✅ Pandas :", pd.__version__)
print("✅ NumPy :", np.__version__)

nlp = spacy.load("en_core_web_sm")

print("✅ spaCy Loaded Successfully")
print("✅ All Libraries Ready")

from google.colab import files

print("Upload ONE Job Description")

uploaded_job = files.upload()

print("\nNow upload one or more resumes")

uploaded_resumes = files.upload()

import fitz
from docx import Document


def read_pdf(file_name):

    text = ""

    pdf = fitz.open(file_name)

    for page in pdf:

        text += page.get_text()

    pdf.close()

    return text



def read_docx(file_name):

    document = Document(file_name)

    text = ""

    for para in document.paragraphs:

        text += para.text + "\n"

    return text


resume_records = []

for resume_name in uploaded_resumes.keys():

    print(f"Reading {resume_name}")

    if resume_name.lower().endswith(".pdf"):

        text = read_pdf(resume_name)

    elif resume_name.lower().endswith(".docx"):

        text = read_docx(resume_name)

    else:

        continue

    resume_records.append({

        "Resume_File": resume_name,

        "Resume_Text": text

    })

print("\n✅ Resume Parsing Completed")

import pandas as pd

resume_df = pd.DataFrame(resume_records)

print("Total Resumes :", len(resume_df))

resume_df.head()

import fitz
from docx import Document


def read_pdf(file_path):

    text = ""

    pdf = fitz.open(file_path)

    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text.strip()



def read_docx(file_path):

    doc = Document(file_path)

    text = ""

    for para in doc.paragraphs:
        text += para.text + "\n"

    return text.strip()


print("✅ Resume Reader Module Loaded Successfully")

resume_records = []

for resume_name in uploaded_resumes.keys():

    print(f"Reading : {resume_name}")

    if resume_name.lower().endswith(".pdf"):

        resume_text = read_pdf(resume_name)

    elif resume_name.lower().endswith(".docx"):

        resume_text = read_docx(resume_name)

    else:

        print("Unsupported File Format")
        continue

    resume_records.append({

        "Resume_File": resume_name,

        "Resume_Text": resume_text

    })

print("\n✅ Resume Parsing Completed Successfully")

import pandas as pd

resume_df = pd.DataFrame(resume_records)

print(f"Total Resumes Parsed : {len(resume_df)}")

display(resume_df.head())

import re


def extract_name(text):

    lines = text.split("\n")

    for line in lines:

        line = line.strip()

        if len(line) > 2:

            if "@" not in line and "linkedin" not in line.lower():

                return line

    return "Not Found"



def extract_email(text):

    pattern = r'[\w\.-]+@[\w\.-]+\.\w+'

    match = re.search(pattern, text)

    if match:
        return match.group()

    return "Not Found"



def extract_phone(text):

    pattern = r'(\+?\d[\d\s\-\(\)]{8,}\d)'

    match = re.search(pattern, text)

    if match:
        return match.group().strip()

    return "Not Found"



def extract_linkedin(text):

    pattern = r'(https?://)?(www\.)?linkedin\.com/in/[A-Za-z0-9\-_]+'

    match = re.search(pattern, text)

    if match:
        return match.group()

    return "Not Found"

print("✅ Information Extraction Functions Ready")

resume_df["Candidate_Name"] = resume_df["Resume_Text"].apply(extract_name)

resume_df["Email"] = resume_df["Resume_Text"].apply(extract_email)

resume_df["Phone"] = resume_df["Resume_Text"].apply(extract_phone)

resume_df["LinkedIn"] = resume_df["Resume_Text"].apply(extract_linkedin)

print("✅ Candidate Information Extracted Successfully")

resume_df[
    [
        "Candidate_Name",
        "Email",
        "Phone",
        "LinkedIn",
        "Resume_File"
    ]
]

import fitz
from docx import Document

job_filename = list(uploaded_job.keys())[0]

if job_filename.lower().endswith(".pdf"):

    job_description_text = read_pdf(job_filename)

elif job_filename.lower().endswith(".docx"):

    job_description_text = read_docx(job_filename)

else:

    raise ValueError("Unsupported Job Description Format")

print("✅ Job Description Loaded Successfully")

print(job_description_text[:3000])

import re

def clean_text(text):

    text = text.lower()

    text = re.sub(r"\n", " ", text)

    text = re.sub(r"\t", " ", text)

    text = re.sub(r"[^a-zA-Z0-9+# ]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()


job_description_clean = clean_text(job_description_text)

print("✅ Job Description Cleaned")

print(job_description_clean[:3000])

import json

recruitment_knowledge_base = {

    "Software Engineer": {

        "weights": {

            "Skills": 40,
            "Experience": 25,
            "Education": 15,
            "Projects": 10,
            "Certifications": 5,
            "Soft_Skills": 5
        },

        "required_skills": [

            "Python",
            "SQL",
            "Git",
            "Data Structures",
            "Algorithms"

        ],

        "preferred_skills": [

            "Docker",
            "AWS",
            "Linux",
            "REST API"

        ],

        "minimum_experience": 2,

        "education": [

            "B.Tech",
            "B.E.",
            "M.Tech"

        ]
    }

}

print("✅ Knowledge Base Created")

with open("recruitment_knowledge_base.json", "w") as file:

    json.dump(recruitment_knowledge_base, file, indent=4)

print("✅ Knowledge Base Saved")

with open("recruitment_knowledge_base.json", "r") as file:

    recruitment_knowledge_base = json.load(file)

print(recruitment_knowledge_base.keys())

from google.colab import files

print("Upload Job Description (PDF or DOCX)")

uploaded_job = files.upload()

job_filename = list(uploaded_job.keys())[0]

if job_filename.lower().endswith(".pdf"):

    job_description_text = read_pdf(job_filename)

elif job_filename.lower().endswith(".docx"):

    job_description_text = read_docx(job_filename)

else:

    raise ValueError("Only PDF and DOCX are supported.")

print("✅ Job Description Loaded Successfully")

print("read_pdf" in globals())
print("read_docx" in globals())

import fitz
from docx import Document


def read_pdf(file_path):
    text = ""

    pdf = fitz.open(file_path)

    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text.strip()



def read_docx(file_path):
    document = Document(file_path)

    text = ""

    for paragraph in document.paragraphs:
        text += paragraph.text + "\n"

    return text.strip()


print("✅ Document Reader Ready")

!pip install -q pymupdf python-docx

import fitz
from docx import Document

print("✅ Libraries Imported Successfully")

def read_pdf(file_path):
    text = ""

    pdf = fitz.open(file_path)

    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text.strip()


def read_docx(file_path):
    document = Document(file_path)

    text = ""

    for paragraph in document.paragraphs:
        text += paragraph.text + "\n"

    return text.strip()


print("✅ Reader Functions Ready")

job_filename = list(uploaded_job.keys())[0]

if job_filename.lower().endswith(".pdf"):
    job_description_text = read_pdf(job_filename)

elif job_filename.lower().endswith(".docx"):
    job_description_text = read_docx(job_filename)

else:
    raise ValueError("Unsupported file format")

print("✅ Job Description Loaded Successfully")

!pip -q install pymupdf
!pip -q install python-docx
!pip -q install sentence-transformers
!pip -q install shap
!pip -q install scikit-learn
!pip -q install pandas
!pip -q install numpy

import fitz
import re
import json
import numpy as np
import pandas as pd

from docx import Document

from sentence_transformers import SentenceTransformer

from sklearn.metrics.pairwise import cosine_similarity

print("✅ All Libraries Imported Successfully")

def read_pdf(file_path):

    text = ""

    pdf = fitz.open(file_path)

    for page in pdf:

        text += page.get_text()

    pdf.close()

    return text


def read_docx(file_path):

    document = Document(file_path)

    text = ""

    for paragraph in document.paragraphs:

        text += paragraph.text + "\n"

    return text


def clean_text(text):

    text = text.lower()

    text = re.sub(r"\n", " ", text)

    text = re.sub(r"\t", " ", text)

    text = re.sub(r"[^a-zA-Z0-9+# ]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()


print("✅ Utility Functions Ready")

from google.colab import files

print("Upload all resumes")

uploaded_resumes = files.upload()

print("Upload Job Description")

uploaded_job = files.upload()

resume_records = []

for file_name in uploaded_resumes.keys():

    if file_name.lower().endswith(".pdf"):

        resume_text = read_pdf(file_name)

    elif file_name.lower().endswith(".docx"):

        resume_text = read_docx(file_name)

    else:

        continue

    resume_records.append({

        "Resume_File": file_name,

        "Resume_Text": resume_text

    })

resume_df = pd.DataFrame(resume_records)

print("Total Resumes :", len(resume_df))

job_filename = list(uploaded_job.keys())[0]

if job_filename.lower().endswith(".pdf"):

    job_description_text = read_pdf(job_filename)

elif job_filename.lower().endswith(".docx"):

    job_description_text = read_docx(job_filename)

else:

    raise ValueError("Unsupported file")

print("✅ Job Description Loaded")

print("Resumes Loaded :", len(resume_df))

print()

print("Job Description Preview")

print("-"*50)

print(job_description_text[:1000])

import re


def extract_name(text):

    lines = text.split("\n")

    for line in lines:

        line = line.strip()

        if len(line) > 2:

            if "@" not in line:

                return line

    return "Not Found"



def extract_email(text):

    pattern = r'[\w\.-]+@[\w\.-]+\.\w+'

    match = re.search(pattern, text)

    if match:

        return match.group()

    return "Not Found"



def extract_phone(text):

    pattern = r'(\+?\d[\d\s\-\(\)]{8,}\d)'

    match = re.search(pattern, text)

    if match:

        return match.group()

    return "Not Found"


print("✅ Candidate Profile Functions Ready")

resume_df["Candidate_Name"] = resume_df["Resume_Text"].apply(extract_name)

resume_df["Email"] = resume_df["Resume_Text"].apply(extract_email)

resume_df["Phone"] = resume_df["Resume_Text"].apply(extract_phone)

print("✅ Candidate Profiles Created")

resume_df[
    [
        "Candidate_Name",
        "Email",
        "Phone",
        "Resume_File"
    ]
]

candidate_profiles = []

for _, row in resume_df.iterrows():

    candidate = {

        "Candidate_Name": row["Candidate_Name"],

        "Email": row["Email"],

        "Phone": row["Phone"],

        "Resume_File": row["Resume_File"],

        "Resume_Text": row["Resume_Text"],

        "Skills": [],

        "Experience": [],

        "Education": [],

        "Projects": [],

        "Certifications": [],

        "Soft_Skills": []

    }

    candidate_profiles.append(candidate)

print("✅ Candidate Profile Objects Created")

print("Total Candidates :", len(candidate_profiles))

candidate_profiles[0]

candidate_profiles[0]

candidate_profiles = []

for _, row in resume_df.iterrows():

    candidate = {

        "Candidate_Name": row["Candidate_Name"],

        "Email": row["Email"],

        "Phone": row["Phone"],

        "Resume_File": row["Resume_File"],

        "Resume_Text": row["Resume_Text"],

        "Skills": [],

        "Experience": [],

        "Education": [],

        "Projects": [],

        "Certifications": [],

        "Soft_Skills": []

    }

    candidate_profiles.append(candidate)

print("✅ Candidate Profiles Created")
print("Total Candidates :", len(candidate_profiles))

candidate_profiles[0]

resume_df.head()

for candidate in candidate_profiles:

    print("=" * 80)

    print("Candidate Name :", candidate["Candidate_Name"])

    print("Email          :", candidate["Email"])

    print("Phone          :", candidate["Phone"])

    print("Resume File    :", candidate["Resume_File"])

    print("=" * 80)

    print()

job_profile = {

    "Job_Title": "",

    "Required_Skills": [],

    "Preferred_Skills": [],

    "Experience": "",

    "Education": [],

    "Responsibilities": [],

    "Job_Text": job_description_text

}

print("✅ Empty Job Profile Created")

import re

def extract_experience(text):

    pattern = r'(\d+)\+?\s*(?:years|year|yrs|yr)'

    match = re.search(pattern, text, re.IGNORECASE)

    if match:

        return match.group(0)

    return "Not Mentioned"

job_profile["Experience"] = extract_experience(
    job_description_text
)

print(job_profile["Experience"])

education_patterns = [

    "B.Tech",

    "B.E",

    "Bachelor",

    "MBA",

    "MCA",

    "M.Tech",

    "BCA",

    "B.Sc",

    "M.Sc",

    "PhD"

]

education_found = []

for degree in education_patterns:

    if degree.lower() in job_description_text.lower():

        education_found.append(degree)

job_profile["Education"] = education_found

print(job_profile["Education"])

education_found = []

jd_text = job_description_text.lower()

for degree in education_patterns:

    if degree.lower() in jd_text:

        education_found.append(degree)

job_profile["Education"] = list(set(education_found))

print("Education Found:")
print(job_profile["Education"])

print(job_profile)

import re

def extract_experience(text):

    pattern = r'(\d+)\s*\+?\s*(?:years|year|yrs|yr)'

    matches = re.findall(pattern, text, flags=re.IGNORECASE)

    if matches:

        years = [int(x) for x in matches]

        return max(years)

    return None

job_profile["Minimum_Experience"] = extract_experience(job_description_text)

print(job_profile["Minimum_Experience"])

import re

def extract_candidate_phrases(text):

    # Split the text into lines
    lines = text.split("\n")

    phrases = []

    for line in lines:

        line = line.strip()

        # Ignore very short lines
        if len(line) < 3:
            continue

        # Ignore headings ending with :
        if line.endswith(":"):
            continue

        phrases.append(line)

    return phrases

jd_phrases = extract_candidate_phrases(job_description_text)

print("Total Phrases:", len(jd_phrases))

for phrase in jd_phrases[:30]:
    print(phrase)

def extract_resume_phrases(text):

    lines = text.split("\n")

    phrases = []

    for line in lines:

        line = line.strip()

        if len(line) < 3:
            continue

        if line.endswith(":"):
            continue

        phrases.append(line)

    return phrases

resume_phrases = extract_resume_phrases(
    candidate_profiles[0]["Resume_Text"]
)

print("Total Resume Phrases :", len(resume_phrases))

for phrase in resume_phrases[:30]:

    print(phrase)

role_model = SentenceTransformer("all-MiniLM-L6-v2")

jd_embeddings = role_model.encode(
    jd_phrases,
    convert_to_numpy=True
)

resume_embeddings = role_model.encode(
    resume_phrases,
    convert_to_numpy=True
)

print("JD Embeddings Shape :", jd_embeddings.shape)
print("Resume Embeddings Shape :", resume_embeddings.shape)

from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(
    jd_embeddings,
    resume_embeddings
)

print(similarity_matrix.shape)

matching_results = []

for candidate in candidate_profiles:

    result = {

        "Candidate_Name": candidate["Candidate_Name"],

        "Resume_File": candidate["Resume_File"],

        "Skill_Match": None,

        "Experience_Match": None,

        "Education_Match": None,

        "Project_Match": None,

        "Certification_Match": None,

        "Semantic_Match": None,

        "Final_Score": None,

        "Rank": None,

        "Recommendation": None

    }

    matching_results.append(result)

print("✅ Matching Result Structure Created")

matching_results[0]

import re

def extract_section(text, section_names):

    lines = text.split("\n")

    extracted_lines = []

    capture = False

    for line in lines:

        current_line = line.strip()

        if not current_line:
            continue

        current_lower = current_line.lower()

        if any(section.lower() in current_lower for section in section_names):

            capture = True
            continue


        if capture:

            if re.match(
                r'^(education|experience|projects|project|certifications|certification|responsibilities|employment|summary|profile|objective|achievements|languages|interests)\b',
                current_lower
            ):
                break

            extracted_lines.append(current_line)

    return extracted_lines

print("✅ Generic Section Extractor Ready")

resume_skill_section = extract_section(

    candidate_profiles[0]["Resume_Text"],

    ["skills", "technical skills", "core competencies"]

)

print(resume_skill_section)

jd_skill_section = extract_section(

    job_description_text,

    ["skills", "required skills", "technical skills", "key skills"]

)

print(jd_skill_section)

def build_candidate_profile(candidate):

    profile = {}

    profile["Candidate_Name"] = candidate["Candidate_Name"]

    profile["Email"] = candidate["Email"]

    profile["Phone"] = candidate["Phone"]

    profile["Resume_File"] = candidate["Resume_File"]

    profile["Skills"] = extract_section(
        candidate["Resume_Text"],
        ["skills", "technical skills", "core competencies"]
    )

    profile["Education"] = extract_education(
        candidate["Resume_Text"]
    )

    profile["Resume_Text"] = candidate["Resume_Text"]

    return profile

print("✅ Candidate Profile Builder Ready")

# ==========================================================
# AI-RDSS
# UTILITIES : Education Extraction
# ==========================================================

def extract_education(text):

    education_patterns = [

        "Bachelor",
        "Bachelor's",
        "B.Tech",
        "B.E",
        "BCA",
        "B.Sc",
        "Master",
        "Master's",
        "MBA",
        "M.Tech",
        "MCA",
        "M.Sc",
        "PhD",
        "Diploma"

    ]

    education_found = []

    text = text.lower()

    for degree in education_patterns:

        if degree.lower() in text:

            education_found.append(degree)

    return sorted(list(set(education_found)))

print("✅ extract_education() Loaded Successfully")

print("extract_education" in globals())

structured_candidates = []

for candidate in candidate_profiles:
    profile = build_candidate_profile(candidate)

    print(profile.keys())      # <-- check
    structured_candidates.append(profile)

print(structured_candidates[0]["Skills"])

print("extract_education" in globals())

structured_candidates = []

for candidate in candidate_profiles:

    structured_candidates.append(
        build_candidate_profile(candidate)
    )

print("✅ Structured Candidate Profiles Created")

def build_candidate_profile(candidate):

    profile = {

        "Candidate_ID": "",

        "Candidate_Name": candidate.get("Candidate_Name", ""),

        "Email": candidate.get("Email", ""),

        "Phone": candidate.get("Phone", ""),

        "Resume_File": candidate.get("Resume_File", ""),

        "Job_Applied": "",

        "Skills": extract_candidate_skills(
    candidate.get("Resume_Text", ""),
    required_skills,
    preferred_skills
),

        "Experience": [],

        "Education": extract_education(
            candidate.get("Resume_Text", "")
        ),

        "Projects": [],

        "Certifications": [],

        "Soft_Skills": [],

        "Achievements": [],

        "Languages": [],

        "Resume_Text": candidate.get("Resume_Text", "")

    }

    return profile

print("✅ Candidate Profile Builder Ready")

structured_candidates = []

for candidate in candidate_profiles:

    structured_candidates.append(
        build_candidate_profile(candidate)
    )

print("✅ Structured Candidate Profiles Created")

structured_candidates[0]

def build_job_profile(job_text):

    profile = {

        "Job_ID": "JOB001",

        "Job_Title": "",

        "Department": "",

        "Employment_Type": "",

        "Location": "",

        "Required_Skills": [],

        "Preferred_Skills": [],

        "Experience": "",

        "Education": extract_education(job_text),

        "Responsibilities": [],

        "Soft_Skills": [],

        "Job_Text": job_text

    }

    return profile

print("✅ Job Profile Builder Ready")

job_profile = build_job_profile(job_description_text)

print(job_profile)

import re

def extract_required_skills(job_text):

    section_headings = [

        "required skills",
        "technical skills",
        "key skills",
        "skills",
        "requirements",
        "qualifications"

    ]

    skills = extract_section(job_text, section_headings)

    cleaned_skills = []

    for item in skills:

        item = item.strip("•-* \t")

        if len(item) > 1:

            cleaned_skills.append(item)

    return list(dict.fromkeys(cleaned_skills))

print("✅ Required Skill Extractor Ready")

job_profile["Required_Skills"] = extract_required_skills(
    job_description_text
)

print(job_profile["Required_Skills"])

import re

def split_into_sentences(text):

    text = re.sub(r'\s+', ' ', text).strip()

    sentences = re.split(r'(?<=[.!?])\s+', text)

    sentences = [s.strip() for s in sentences if s.strip()]

    return sentences

print("✅ Sentence Splitter Ready")

jd_sentences = split_into_sentences(job_description_text)

print("Total Sentences:", len(jd_sentences))

for i, sentence in enumerate(jd_sentences, start=1):

    print(f"{i}. {sentence}")

print(job_description_text[:1500])

import re

def extract_jd_sections(text):

    headings = [
        "Key Responsibilities",
        "Key Tasks and Duties",
        "Education and Certification Requirements",
        "Qualifications",
        "Required Skills",
        "Preferred Skills",
        "Experience",
        "Technical Skills"
    ]

    sections = {}

    current_heading = "General"

    sections[current_heading] = []

    lines = text.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        matched = False

        for heading in headings:

            if heading.lower() == line.lower():

                current_heading = heading

                sections[current_heading] = []

                matched = True

                break

        if not matched:

            sections[current_heading].append(line)

    return sections

print("✅ JD Section Extractor Ready")

jd_sections = extract_jd_sections(job_description_text)

print(jd_sections.keys())

for heading, content in jd_sections.items():

    print("\n==============================")

    print(heading)

    print("==============================")

    for line in content:

        print(line)

job_profile = {

    "Job_ID":"JOB001",

    "Job_Title":"",

    "Responsibilities":jd_sections.get(
        "Key Responsibilities", []
    ),

    "Tasks":jd_sections.get(
        "Key Tasks and Duties", []
    ),

    "Education":[],

    "Technical_Skills":[],

    "Soft_Skills":[],

    "Certifications":[],

    "Experience":[],

    "Job_Text":job_description_text

}

print("✅ Structured Job Profile Created")

print(job_profile)

skill_knowledge_base = {
    "Programming": [
        "Python","Java","C","C++","JavaScript","SQL"
    ],
    "Web Development": [
        "HTML","CSS","React","Node.js","Express","REST API"
    ],
    "Database": [
        "MySQL","PostgreSQL","MongoDB","SQLite"
    ],
    "Cloud": [
        "AWS","Azure","GCP"
    ],
    "DevOps": [
        "Docker","Kubernetes","Git","GitHub","Linux"
    ],
    "AI/ML": [
        "Machine Learning","Deep Learning","TensorFlow",
        "PyTorch","Scikit-learn","NLP"
    ]
}

print("✅ Skill Knowledge Base Loaded")

import re

def extract_technical_skills(job_text):

    words = re.findall(r"[A-Za-z0-9\+\#\.]+", job_text)

    skills = []

    # Read all skills from knowledge base
    for category, category_skills in skill_knowledge_base.items():

        for skill in category_skills:

            if skill.lower() in job_text.lower():

                skills.append(skill)

    return sorted(list(set(skills)))

print("✅ Dynamic Skill Extractor Ready")

job_skills = extract_technical_skills(job_description_text)

print(job_skills)

print(recruitment_knowledge_base.keys())

print(recruitment_knowledge_base["Software Engineer"].keys())

job_title = "Software Engineer"

job_requirements = recruitment_knowledge_base[job_title]

required_skills = job_requirements["required_skills"]

preferred_skills = job_requirements["preferred_skills"]

minimum_experience = job_requirements["minimum_experience"]

required_education = job_requirements["education"]

weights = job_requirements["weights"]

print("✅ Job Requirements Loaded")

print("Job Title :", job_title)

print("\nRequired Skills")
print(required_skills)

print("\nPreferred Skills")
print(preferred_skills)

print("\nMinimum Experience")
print(minimum_experience)

print("\nEducation")
print(required_education)

print("\nWeights")
print(weights)

from sklearn.metrics.pairwise import cosine_similarity

def semantic_skill_matching(candidate_skills,
                            required_skills,
                            model):

    matched_skills = []

    missing_skills = []

    similarity_scores = []

    if len(candidate_skills) == 0:

        return matched_skills, missing_skills, 0

    candidate_embeddings = model.encode(
        candidate_skills,
        convert_to_tensor=False
    )

    required_embeddings = model.encode(
        required_skills,
        convert_to_tensor=False
    )

    for i, required_skill in enumerate(required_skills):

        similarities = cosine_similarity(
            [required_embeddings[i]],
            candidate_embeddings
        )[0]

        best_score = max(similarities)

        best_index = similarities.argmax()

        if best_score >= 0.60:

            matched_skills.append({

                "Required Skill": required_skill,

                "Matched Skill": candidate_skills[best_index],

                "Similarity": round(float(best_score),3)

            })

            similarity_scores.append(best_score)

        else:

            missing_skills.append(required_skill)

    if len(required_skills) == 0:

        overall_score = 0

    else:

        overall_score = round(
            (len(matched_skills) / len(required_skills)) * 100,
            2
        )

    return matched_skills, missing_skills, overall_score


print("✅ Semantic Matching Engine Ready")

candidate_skills = structured_candidates[0]["Skills"]

matched_skills, missing_skills, skill_score = semantic_skill_matching(

    candidate_skills,

    required_skills,

    role_model

)

print("Matched Skills\n")

for skill in matched_skills:

    print(skill)

print("\n----------------------")

print("Missing Skills\n")

for skill in missing_skills:

    print(skill)

print("\n----------------------")

print("Skill Match Score")

print(skill_score,"%")

import re

def extract_candidate_skills(resume_text, required_skills, preferred_skills):

    resume_lower = resume_text.lower()

    extracted_skills = []

    all_skills = list(set(required_skills + preferred_skills))

    for skill in all_skills:

        pattern = r'\b' + re.escape(skill.lower()) + r'\b'

        if re.search(pattern, resume_lower):

            extracted_skills.append(skill)

    return sorted(extracted_skills)

print("✅ Candidate Skill Extractor Ready")

for candidate in structured_candidates:

    candidate["Skills"] = extract_candidate_skills(

        candidate["Resume_Text"],

        required_skills,

        preferred_skills

    )

print("✅ Candidate Skills Extracted")

structured_candidates[0]["Skills"]

candidate_skills = structured_candidates[0]["Skills"]

matched_skills, missing_skills, skill_score = semantic_skill_matching(

    candidate_skills,

    required_skills,

    role_model

)

print("Skill Score :", skill_score)
print("\nMatched Skills")
print(matched_skills)

print("\nMissing Skills")
print(missing_skills)

import re

def extract_experience_years(text):

    patterns = [

        r'(\d+)\+?\s*years',

        r'(\d+)\+?\s*year',

        r'(\d+)\+?\s*yrs',

        r'(\d+)\+?\s*yr'

    ]

    years = []

    for pattern in patterns:

        matches = re.findall(pattern, text.lower())

        years.extend(matches)

    if len(years) == 0:

        return 0

    years = [int(i) for i in years]

    return max(years)

print("✅ Experience Extractor Ready")

for candidate in structured_candidates:

    candidate["Experience_Years"] = extract_experience_years(
        candidate["Resume_Text"]
    )

print("✅ Experience Added")

structured_candidates[0]["Experience_Years"]

def education_match(candidate_education,
                    required_education):

    if isinstance(required_education, list):

        required = " ".join(required_education).lower()

    else:

        required = str(required_education).lower()

    candidate = " ".join(candidate_education).lower()

    if required in candidate:

        return 100

    return 0

print("✅ Education Matching Ready")

education_score = education_match(

    structured_candidates[0]["Education"],

    required_education

)

print(education_score)

def calculate_experience_score(candidate_years, required_years):

    if required_years == 0:

        return 100

    if candidate_years >= required_years:

        return 100

    score = (candidate_years / required_years) * 100

    return round(score,2)



def calculate_final_score(skill_score,
                          experience_score,
                          education_score,
                          weights):


    final_score = (

        skill_score * weights.get("skill",0)

        +

        experience_score * weights.get("experience",0)

        +

        education_score * weights.get("education",0)

    )


    return round(final_score,2)



print("✅ Hybrid Scoring Engine Ready")

required_experience = recruitment_knowledge_base[job_title]["minimum_experience"]


candidate_years = structured_candidates[0]["Experience_Years"]


experience_score = calculate_experience_score(

    candidate_years,

    required_experience

)


print("Experience Score :", experience_score)

final_score = calculate_final_score(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("Candidate Final Score :", final_score,"%")

def recommendation(score):

    if score >= 85:

        return "Strongly Recommended"

    elif score >= 70:

        return "Recommended"

    elif score >= 50:

        return "Review Required"

    else:

        return "Not Recommended"



decision = recommendation(final_score)


print("Recruiter Decision :", decision)

def generate_reason(candidate):

    reasons = []

    if candidate["Skill_Score"] >= 80:

        reasons.append(
            "Strong skill match"
        )

    elif candidate["Skill_Score"] >= 50:

        reasons.append(
            "Moderate skill match"
        )

    else:

        reasons.append(
            "Low skill match"
        )


    if candidate["Experience_Score"] >= 80:

        reasons.append(
            "Experience requirement satisfied"
        )

    else:

        reasons.append(
            "Experience gap identified"
        )


    if candidate["Education_Score"] == 100:

        reasons.append(
            "Education requirement satisfied"
        )

    else:

        reasons.append(
            "Education mismatch"
        )


    return reasons



def rank_candidates(candidate_results):


    ranked = sorted(

        candidate_results,

        key=lambda x: x["Final_Score"],

        reverse=True

    )


    for index, candidate in enumerate(ranked, start=1):

        candidate["Rank"] = index

        candidate["Reason"] = generate_reason(candidate)


    return ranked



print("✅ Candidate Ranking Engine Ready")

candidate_results = []

for candidate in structured_candidates:

    candidate_skills = candidate["Skills"]

    matched_skills, missing_skills, skill_score = semantic_skill_matching(
        candidate_skills,
        required_skills,
        role_model
    )

    candidate_years = extract_real_experience(
        candidate["Resume_Text"]
    )

    experience_score = calculate_experience_score(
        candidate_years,
        required_exp
    )

    education_score = get_education_score(
        candidate["Education"],
        required_education
    )

    final_score = calculate_final_score_final(
        skill_score,
        experience_score,
        education_score,
        weights
    )

    candidate_results.append({

        "Candidate_Name": candidate["Candidate_Name"],

        "Skill_Score": skill_score,
        "Experience_Score": experience_score,
        "Education_Score": education_score,
        "Final_Score": final_score

    })

print(pd.DataFrame(candidate_results))

ranked_candidates = rank_candidates(
    candidate_results
)


for candidate in ranked_candidates:

    print("\nRank:", candidate["Rank"])

    print(
        "Candidate:",
        candidate["Candidate_Name"]
    )

    print(
        "Score:",
        candidate["Final_Score"],
        "%"
    )

    print(
        "Reason:",
        candidate["Reason"]
    )

import pandas as pd


def create_explanation_dataframe(candidate):


    data = {

        "Skill_Score":[
            candidate["Skill_Score"]
        ],

        "Experience_Score":[
            candidate["Experience_Score"]
        ],

        "Education_Score":[
            candidate["Education_Score"]
        ]

    }


    return pd.DataFrame(data)



print("✅ SHAP Data Preparation Ready")

!pip install shap -q

def decision_model(X):

    scores = (

        X["Skill_Score"] * weights.get("skill",0)

        +

        X["Experience_Score"] * weights.get("experience",0)

        +

        X["Education_Score"] * weights.get("education",0)

    )

    return scores.values



print("✅ Decision Model Ready")

shap_dataset = create_shap_dataset(candidate_results)

print(shap_dataset)

import pandas as pd
import shap


def create_shap_dataset(candidate_results):

    data = []

    for candidate in candidate_results:

        data.append({

            "Skill_Score": candidate["Skill_Score"],

            "Experience_Score": candidate["Experience_Score"],

            "Education_Score": candidate["Education_Score"]

        })

    return pd.DataFrame(data)


shap_dataset = create_shap_dataset(candidate_results)


print(shap_dataset)

for i, c in enumerate(candidate_profiles):
    print(f"\nCandidate {i+1}")
    print(c)

explainer = shap.Explainer(

    decision_model,

    shap_dataset

)


shap_values = explainer(
    shap_dataset
)


print("✅ SHAP Values Generated")

print("="*70)
print("SHAP SUMMARY PLOT")
print("="*70)

shap.summary_plot(shap_values, shap_dataset)
plt.savefig("SHAP_Summary.png", dpi=300, bbox_inches="tight")
print("✅ SHAP image saved successfully")



print("="*70)
print("SHAP BAR PLOT")
print("="*70)

shap.plots.bar(shap_values)

def generate_candidate_explanation(candidate):

    explanation = []

    # Skills
    if candidate["Skill_Score"] >= 70:
        explanation.append("✔ Strong skill match with Job Description")
    elif candidate["Skill_Score"] >= 40:
        explanation.append("✔ Partial skill match with Job Description")
    else:
        explanation.append("✘ Low skill match with Job Description")

    # Experience
    if candidate["Experience_Score"] >= 80:
        explanation.append("✔ Relevant work experience found")
    elif candidate["Experience_Score"] > 0:
        explanation.append("✔ Some relevant experience found")
    else:
        explanation.append("✘ No relevant experience found")

    # Education
    if candidate["Education_Score"] >= 100:
        explanation.append("✔ Required education satisfied")
    else:
        explanation.append("✘ Education partially matched")

    # Recommendation
    if candidate["Final_Score"] >= 80:
        recommendation = "Highly Recommended"
    elif candidate["Final_Score"] >= 60:
        recommendation = "Recommended"
    elif candidate["Final_Score"] >= 40:
        recommendation = "Consider for Interview"
    else:
        recommendation = "Not Recommended"

    return explanation, recommendation

print("="*80)
print("AI CANDIDATE EXPLANATION")
print("="*80)

for i, candidate in enumerate(ranked_candidates, start=1):

    explanation, recommendation = generate_candidate_explanation(candidate)

    print("\nCandidate :", candidate["Candidate_Name"])
    print("Rank :", i)
    print("Score :", candidate["Final_Score"])
    print("\nReason:")

    for reason in explanation:
        print(reason)

    print("\nRecommendation :", recommendation)

    print("-"*80)

def generate_explanation(skill_score,
                         experience_score,
                         education_score,
                         weights):


    explanation = {


        "Skill Contribution":

        round(skill_score * weights.get("skill",0),2),


        "Experience Contribution":

        round(experience_score * weights.get("experience",0),2),


        "Education Contribution":

        round(education_score * weights.get("education",0),2)

    }


    return explanation



explanation = generate_explanation(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("✅ Explanation Generated")



for factor, value in explanation.items():

    print(
        factor,
        ":",
        value
    )

candidate_skills = structured_candidates[0]["Skills"]


matched_skills, missing_skills, skill_score = semantic_skill_matching(

    candidate_skills,

    required_skills,

    role_model

)


candidate_years = structured_candidates[0]["Experience_Years"]


experience_score = calculate_experience_score(

    candidate_years,

    required_experience

)


education_score = education_match(

    structured_candidates[0]["Education"],

    required_education

)


final_score = calculate_final_score(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("Skill Score:", skill_score)

print("Experience Score:", experience_score)

print("Education Score:", education_score)

print("Final Score:", final_score)

print("========== CANDIDATE PROFILE ==========")

print("Experience Field:")
print(structured_candidates[0]["Experience_Years"])

print("\nEducation Field:")
print(structured_candidates[0]["Education"])


print("\n========== JOB REQUIREMENT ==========")

print("Minimum Experience:")
print(required_experience)

print("\nRequired Education:")
print(required_education)

import re


def get_experience_score(candidate_text, required_text):

    # Extract candidate years

    candidate_match = re.findall(
        r'(\d+)\+?\s*(?:years|year|yrs|yr)',
        candidate_text.lower()
    )

    if candidate_match:

        candidate_years = max(
            [int(x) for x in candidate_match]
        )

    else:

        candidate_years = 0


    # Extract required years

    required_match = re.findall(
        r'(\d+)',
        str(required_text)
    )

    if required_match:

        required_years = int(required_match[0])

    else:

        required_years = 0


    if required_years == 0:

        return 100


    if candidate_years >= required_years:

        return 100


    return round(
        (candidate_years / required_years) * 100,
        2
    )



def get_education_score(candidate_education,
                        required_education):


    candidate_text = str(
        candidate_education
    ).lower()


    required_text = str(
        required_education
    ).lower()


    candidate_words = set(
        re.findall(r'\w+', candidate_text)
    )


    required_words = set(
        re.findall(r'\w+', required_text)
    )


    match = len(
        candidate_words.intersection(required_words)
    )


    if match > 0:

        return 100


    return 0



# Recalculate

experience_score = get_experience_score(

    structured_candidates[0]["Resume_Text"],

    required_experience

)


education_score = get_education_score(

    structured_candidates[0]["Education"],

    required_education

)


final_score = calculate_final_score(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("Skill Score :", skill_score)

print("Experience Score :", experience_score)

print("Education Score :", education_score)

print("Final Score :", final_score)

final_candidate_result = {

    "Candidate_Name":
    structured_candidates[0]["Candidate_Name"],


    "Skills":
    structured_candidates[0]["Skills"],


    "Skill_Score":
    skill_score,


    "Experience_Score":
    experience_score,


    "Education_Score":
    education_score,


    "Final_Score":
    final_score,


    "Decision":
    recommendation(final_score)

}


print("✅ Final Candidate Result Created")

print(final_candidate_result)

final_candidate_result["Reason"] = []


if skill_score >= 70:

    final_candidate_result["Reason"].append(
        "Strong skill alignment with job requirements"
    )


if experience_score >= 70:

    final_candidate_result["Reason"].append(
        "Experience requirement satisfied"
    )


if education_score >= 70:

    final_candidate_result["Reason"].append(
        "Education requirement satisfied"
    )


print(final_candidate_result["Reason"])

print("================================")

print("Candidate Name :",
      final_candidate_result["Candidate_Name"])

print("Final Score :",
      final_candidate_result["Final_Score"],
      "%")

print("Decision :",
      final_candidate_result["Decision"])

print("\nReasons:")

for r in final_candidate_result["Reason"]:

    print("✓", r)

print("================================")

print("Current Weights:")
print(weights)


def calculate_final_score_fixed(skill_score,
                                experience_score,
                                education_score,
                                weights):


    skill_weight = (
        weights.get("skill",
        weights.get("skills",0))
    )


    experience_weight = (
        weights.get("experience",0)
    )


    education_weight = (
        weights.get("education",0)
    )


    final_score = (

        skill_score * skill_weight

        +

        experience_score * experience_weight

        +

        education_score * education_weight

    )


    return round(final_score,2)



final_score = calculate_final_score_fixed(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("New Final Score:", final_score)

final_candidate_result["Final_Score"] = final_score

final_candidate_result["Decision"] = recommendation(final_score)


print(final_candidate_result)

resume_text = structured_candidates[0]["Resume_Text"].lower()



experience_numbers = re.findall(

    r'\d+',

    resume_text

)


if experience_numbers:

    candidate_experience = max(
        [int(x) for x in experience_numbers]
    )

else:

    candidate_experience = 0



required_numbers = re.findall(

    r'\d+',

    str(required_experience)

)


if required_numbers:

    required_exp = int(required_numbers[0])

else:

    required_exp = 0



if required_exp == 0:

    experience_score = 100

elif candidate_experience >= required_exp:

    experience_score = 100

else:

    experience_score = round(
        (candidate_experience / required_exp) * 100,
        2
    )




education_text = str(
    structured_candidates[0]["Education"]
).lower()


if (
    "bachelor" in education_text
    or
    "b.tech" in education_text
    or
    "b.e" in education_text
):

    education_score = 100

else:

    education_score = 0



print("Candidate Experience:", candidate_experience)

print("Experience Score:", experience_score)

print("Education Score:", education_score)

import re


def extract_real_experience(text):

    text = text.lower()

    patterns = [

        r'(\d+)\+?\s*(?:years|year|yrs|yr)',

        r'experience\s*[:\-]?\s*(\d+)',

        r'(\d+)\+?\s*months'

    ]

    years = []

    for pattern in patterns:

        matches = re.findall(pattern, text)

        for m in matches:

            value = int(m)

            # ignore phone-like numbers
            if value < 50:

                years.append(value)


    if years:

        return max(years)


    return 0



candidate_experience = extract_real_experience(

    structured_candidates[0]["Resume_Text"]

)


print("Correct Experience Years:", candidate_experience)

experience_score = calculate_experience_score(

    candidate_experience,

    required_exp

)


final_score = calculate_final_score_fixed(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("Skill Score:", skill_score)
print("Experience Score:", experience_score)
print("Education Score:", education_score)
print("Final Score:", final_score)

print("Weights from JSON:")
print(weights)

print("\nWeight keys:")
print(list(weights.keys()))

# ==========================================================
# FINAL SCORE CALCULATION FIX
# ==========================================================


def calculate_final_score_final(skill_score,
                                experience_score,
                                education_score,
                                weights):


    values = list(weights.values())


    # if weights are stored as percentages
    if max(values) > 1:

        skill_weight = values[0] / 100
        experience_weight = values[1] / 100
        education_weight = values[2] / 100

    else:

        skill_weight = values[0]
        experience_weight = values[1]
        education_weight = values[2]


    score = (

        skill_score * skill_weight

        +

        experience_score * experience_weight

        +

        education_score * education_weight

    )


    return round(score,2)



final_score = calculate_final_score_final(

    skill_score,

    experience_score,

    education_score,

    weights

)


print("FINAL SCORE:", final_score)

def complete_final_score(skill_score,
                         experience_score,
                         education_score,
                         projects_score,
                         certification_score,
                         soft_skill_score,
                         weights):


    final_score = (

        skill_score * weights["Skills"] / 100

        +

        experience_score * weights["Experience"] / 100

        +

        education_score * weights["Education"] / 100

        +

        projects_score * weights["Projects"] / 100

        +

        certification_score * weights["Certifications"] / 100

        +

        soft_skill_score * weights["Soft_Skills"] / 100

    )


    return round(final_score,2)


print("✅ Complete Weighted Scoring Ready")

projects_score = 0
certification_score = 0
soft_skill_score = 0


final_score = complete_final_score(

    skill_score,

    experience_score,

    education_score,

    projects_score,

    certification_score,

    soft_skill_score,

    weights

)


print("Final Score:", final_score)

def extract_projects_score(text):

    text = text.lower()


    project_keywords = [

        "project",

        "developed",

        "implemented",

        "built",

        "created",

        "application",

        "system",

        "model"

    ]


    count = 0


    for word in project_keywords:

        if word in text:

            count += 1



    if count >= 3:

        return 100

    elif count >= 1:

        return 60

    else:

        return 0



projects_score = extract_projects_score(

    structured_candidates[0]["Resume_Text"]

)


print("Projects Score:", projects_score)

# ==========================================================
# Certification Score
# ==========================================================


def extract_certification_score(text):

    text = text.lower()


    certification_words = [

        "certification",

        "certificate",

        "certified",

        "aws",

        "azure",

        "oracle",

        "google"

    ]


    for word in certification_words:

        if word in text:

            return 100


    return 0



certification_score = extract_certification_score(

    structured_candidates[0]["Resume_Text"]

)


print("Certification Score:", certification_score)

def keyword_match_score(resume_text, requirement_list):

    resume_text = resume_text.lower()

    if not requirement_list:

        return 0


    matched = 0


    for item in requirement_list:

        if item.lower() in resume_text:

            matched += 1


    score = (
        matched / len(requirement_list)
    ) * 100


    return round(score,2)



job_data = recruitment_knowledge_base["Software Engineer"]


# Projects
projects_score = keyword_match_score(

    structured_candidates[0]["Resume_Text"],

    job_data.get("projects", [])

)



# Certifications
certification_score = keyword_match_score(

    structured_candidates[0]["Resume_Text"],

    job_data.get("certifications", [])

)



# Soft Skills
soft_skill_score = keyword_match_score(

    structured_candidates[0]["Resume_Text"],

    job_data.get("soft_skills", [])

)



print("Projects Score:", projects_score)

print("Certification Score:", certification_score)

print("Soft Skill Score:", soft_skill_score)

print(recruitment_knowledge_base["Software Engineer"])

candidate_results = []


candidate_results.append({

    "Candidate_Name":
    structured_candidates[0]["Candidate_Name"],


    "Skills":
    structured_candidates[0]["Skills"],


    "Skill_Score":
    skill_score,


    "Experience_Score":
    experience_score,


    "Education_Score":
    education_score,


    "Final_Score":
    round(final_score,2)

})


print("✅ Candidate Result Added")

print(candidate_results)

ranked_candidates = sorted(

    candidate_results,

    key=lambda x: x["Final_Score"],

    reverse=True

)


for i, candidate in enumerate(
    ranked_candidates,
    start=1
):

    candidate["Rank"] = i


print("✅ Ranking Completed")


for candidate in ranked_candidates:

    print(
        "Rank:",
        candidate["Rank"]
    )

    print(
        "Name:",
        candidate["Candidate_Name"]
    )

    print(
        "Score:",
        candidate["Final_Score"]
    )

    print("----------------")

print("Total Candidates:", len(structured_candidates))

for i, candidate in enumerate(structured_candidates):
    print(i+1, candidate["Candidate_Name"], candidate["Resume_File"])

for i, candidate in enumerate(structured_candidates):
    print("="*70)
    print("Candidate:", candidate["Candidate_Name"])
    print("Skills:")
    print(candidate["Skills"])

candidate_results = []


for candidate in structured_candidates:

    matched_skills, missing_skills, skill_score = semantic_skill_matching(

        candidate["Skills"],

        required_skills,

        role_model

    )


    experience_score = get_experience_score(

        candidate["Resume_Text"],

        required_experience

    )


    education_score = get_education_score(

        candidate["Education"],

        required_education

    )


    final_score = (

        skill_score * weights["Skills"] / 100

        +

        experience_score * weights["Experience"] / 100

        +

        education_score * weights["Education"] / 100

    )


    candidate_results.append({

        "Candidate_Name": candidate["Candidate_Name"],

        "Skill_Score": round(skill_score,2),

        "Experience_Score": round(experience_score,2),

        "Education_Score": round(education_score,2),

        "Final_Score": round(final_score,2),

        "Matched_Skills": matched_skills,

        "Missing_Skills": missing_skills

    })


print("✅ All Candidates Scored\n")


for c in candidate_results:

    print("Candidate:", c["Candidate_Name"])

    print("Final Score:", c["Final_Score"])

    print("Matched Skills:", c["Matched_Skills"])

    print("-------------------------")

ranked_candidates = sorted(

    candidate_results,

    key=lambda x: x["Final_Score"],

    reverse=True

)


print("==============================")
print(" AI-RDSS Candidate Ranking ")
print("==============================")


for rank, candidate in enumerate(
    ranked_candidates,
    start=1
):

    print("\nRank:", rank)

    print(
        "Candidate:",
        candidate["Candidate_Name"]
    )

    print(
        "Score:",
        candidate["Final_Score"],
        "%"
    )

    print(
        "Matched Skills:",
        candidate["Matched_Skills"]
    )

    print(
        "Missing Skills:",
        candidate["Missing_Skills"]
    )

    if candidate["Final_Score"] >= 75:

        print(
            "Recommendation: Strongly Recommended"
        )

    elif candidate["Final_Score"] >= 50:

        print(
            "Recommendation: Review Required"
        )

    else:

        print(
            "Recommendation: Not Recommended"
        )

    print("------------------------------")

import pandas as pd


def skill_to_text(skill_list):

    if not skill_list:
        return ""

    output = []

    for item in skill_list:

        if isinstance(item, dict):

            if "skill" in item:
                output.append(item["skill"])

            elif "name" in item:
                output.append(item["name"])

            else:
                output.append(str(item))

        else:

            output.append(str(item))


    return ", ".join(output)



ranking_table = []


for rank, candidate in enumerate(ranked_candidates, start=1):

    ranking_table.append({

        "Rank": rank,

        "Candidate Name":
        candidate["Candidate_Name"],

        "Final Score (%)":
        candidate["Final_Score"],

        "Skill Score":
        candidate["Skill_Score"],

        "Experience Score":
        candidate["Experience_Score"],

        "Education Score":
        candidate["Education_Score"],

        "Matched Skills":
        skill_to_text(candidate["Matched_Skills"]),

        "Missing Skills":
        skill_to_text(candidate["Missing_Skills"])

    })


df_ranking = pd.DataFrame(ranking_table)


print("✅ Final Ranking Table Created")

df_ranking

for candidate in ranked_candidates:

    score = candidate["Final_Score"]


    if score >= 75:

        decision = "Strongly Recommended"

    elif score >= 50:

        decision = "Recommended for Review"

    else:

        decision = "Not Recommended"



    candidate["Decision"] = decision



final_report = pd.DataFrame(ranked_candidates)


print("✅ AI-RDSS Final Recruitment Report Generated")


final_report[
    [
        "Candidate_Name",
        "Final_Score",
        "Decision",
        "Matched_Skills",
        "Missing_Skills"
    ]
]

import numpy as np


X = []


for candidate in ranked_candidates:

    X.append([

        candidate["Skill_Score"],

        candidate["Experience_Score"],

        candidate["Education_Score"]

    ])


X = np.array(X)


print("SHAP Input Created")

print(X)

from sklearn.linear_model import LinearRegression
import shap


y = np.array(

    [
        c["Final_Score"]

        for c in ranked_candidates
    ]

)


shap_model = LinearRegression()


shap_model.fit(

    X,

    y

)


explainer = shap.Explainer(

    shap_model,

    X

)


shap_values = explainer(X)


print("✅ SHAP Explanation Ready")

shap.plots.waterfall(

    shap_values[0]

)

import pandas as pd
import shap


X_df = pd.DataFrame(

    X,

    columns=[

        "Skill Score",

        "Experience Score",

        "Education Score"

    ]

)


shap_model.fit(

    X_df,

    y

)


explainer = shap.Explainer(

    shap_model,

    X_df

)


shap_values = explainer(X_df)


print("✅ SHAP Features Updated")

print(X_df.columns)

shap.plots.waterfall(

    shap_values[0]

)

print(X_df)
print("\nCandidate Results:")
print(candidate_results)

import pandas as pd
import shap


X_df = pd.DataFrame(

    [

        [
            c["Skill_Score"],
            c["Experience_Score"],
            c["Education_Score"]
        ]

        for c in candidate_results

    ],

    columns=[
        "Skill Score",
        "Experience Score",
        "Education Score"
    ]

)


y = pd.Series(

    [
        c["Final_Score"]

        for c in candidate_results
    ]

)


print(X_df)

model = LinearRegression()

model.fit(X_df, y)


explainer = shap.Explainer(

    model,

    X_df

)


shap_values = explainer(X_df)


shap.plots.waterfall(shap_values[0])

# ==========================================================
# AI-RDSS
# SHAP Explanation Using Actual Scores
# ==========================================================

import shap
import numpy as np


# Take first candidate

candidate = candidate_results[0]


features = np.array([

    candidate["Skill_Score"],

    candidate["Experience_Score"],

    candidate["Education_Score"]

])


feature_names = [

    "Skill Score",

    "Experience Score",

    "Education Score"

]


print("Features Going To SHAP:")

for name, value in zip(feature_names, features):

    print(name, ":", value)



# Actual contribution based on weights

contributions = np.array([

    candidate["Skill_Score"] * weights["Skills"]/100,

    candidate["Experience_Score"] * weights["Experience"]/100,

    candidate["Education_Score"] * weights["Education"]/100

])


print("\nActual Contributions:")

for name, value in zip(feature_names, contributions):

    print(name, ":", value)

print("STRUCTURED CANDIDATE EDUCATION:")
print(structured_candidates[0]["Education"])

print("\nSTRUCTURED CANDIDATE EXPERIENCE:")
print(structured_candidates[0].get("Experience"))

print("\nCURRENT RESULT:")
print(candidate_results[0])

# ==========================================================
# FIX EDUCATION + EXPERIENCE SCORING
# ==========================================================


def fixed_education_score(candidate_education, required_education):

    if not candidate_education:

        return 0


    candidate_text = " ".join(candidate_education).lower()


    for edu in required_education:

        if edu.lower() in candidate_text:

            return 100


    # Bachelor degree detection

    if "bachelor" in candidate_text:

        return 100


    return 0



def fixed_experience_score(resume_text, minimum_experience):

    import re


    matches = re.findall(

        r'(\d+)\+?\s*(?:years|year|yrs|yr)',

        resume_text.lower()

    )


    if matches:

        experience = max(

            [int(x) for x in matches]

        )

    else:

        experience = 0



    if experience >= minimum_experience:

        return 100

    elif experience > 0:

        return 50

    else:

        return 0



for i, candidate in enumerate(structured_candidates):


    exp_score = fixed_experience_score(

        candidate["Resume_Text"],

        job_data["minimum_experience"]

    )


    edu_score = fixed_education_score(

        candidate["Education"],

        job_data["education"]

    )


    candidate_results[i]["Experience_Score"] = exp_score

    candidate_results[i]["Education_Score"] = edu_score



    candidate_results[i]["Final_Score"] = round(

        candidate_results[i]["Skill_Score"] * weights["Skills"]/100

        +

        exp_score * weights["Experience"]/100

        +

        edu_score * weights["Education"]/100,

        2

    )


print(candidate_results)

for c in candidate_results:
    print(c["Candidate_Name"])
    print("Skill:", c["Skill_Score"])
    print("Experience:", c["Experience_Score"])
    print("Education:", c["Education_Score"])
    print("Final:", c["Final_Score"])
    print("----------------")

# ==========================================================
# SHAP INPUT FROM UPDATED CANDIDATE RESULTS
# ==========================================================

import pandas as pd
import shap


shap_data = []


for c in candidate_results:

    shap_data.append([

        c["Skill_Score"],

        c["Experience_Score"],

        c["Education_Score"]

    ])


X_shap = pd.DataFrame(

    shap_data,

    columns=[

        "Skill Score",

        "Experience Score",

        "Education Score"

    ]

)


print(X_shap)

# ==========================================================
# AI-RDSS Explainability
# ==========================================================


weights_array = [

    weights["Skills"]/100,

    weights["Experience"]/100,

    weights["Education"]/100

]


for index, row in X_shap.iterrows():

    print("\nCandidate:",
          candidate_results[index]["Candidate_Name"])


    print("Feature Contributions:")


    for feature, value, weight in zip(

        X_shap.columns,

        row,

        weights_array

    ):

        print(

            feature,

            ":",

            round(value * weight,2)

        )

# ==========================================================
# AI-RDSS
# Explainability Visualization
# ==========================================================

import matplotlib.pyplot as plt


candidate = candidate_results[0]


features = [

    "Skill Score",

    "Experience Score",

    "Education Score"

]


contributions = [

    candidate["Skill_Score"] * weights["Skills"]/100,

    candidate["Experience_Score"] * weights["Experience"]/100,

    candidate["Education_Score"] * weights["Education"]/100

]


plt.figure(figsize=(8,5))


plt.bar(

    features,

    contributions

)


plt.xlabel("Features")

plt.ylabel("Contribution to Final Score")


plt.title(

    "AI-RDSS Decision Explanation - "

    + candidate["Candidate_Name"]

)


plt.xticks(rotation=30)


plt.show()

import matplotlib.pyplot as plt


candidate = candidate_results[1]


features = [

    "Skill Score",

    "Experience Score",

    "Education Score"

]


contributions = [

    candidate["Skill_Score"] * weights["Skills"]/100,

    candidate["Experience_Score"] * weights["Experience"]/100,

    candidate["Education_Score"] * weights["Education"]/100

]


plt.figure(figsize=(8,5))


plt.bar(

    features,

    contributions

)


plt.xlabel("Features")

plt.ylabel("Contribution to Final Score")


plt.title(

    "AI-RDSS Decision Explanation - "

    + candidate["Candidate_Name"]

)


plt.xticks(rotation=30)


plt.show()

import pandas as pd


final_report = []


for rank, candidate in enumerate(

    ranked_candidates,

    start=1

):

    final_report.append({

        "Rank":

        rank,


        "Candidate Name":

        candidate["Candidate_Name"],


        "Final Score (%)":

        candidate["Final_Score"],


        "Decision":

        candidate["Decision"],


        "Skill Score":

        candidate["Skill_Score"],


        "Experience Score":

        candidate["Experience_Score"],


        "Education Score":

        candidate["Education_Score"],


        "Matched Skills":

        candidate["Matched_Skills"],


        "Missing Skills":

        candidate["Missing_Skills"]

    })



final_report_df = pd.DataFrame(final_report)


print("✅ AI-RDSS Final Recruitment Report")

final_report_df

final_report_df.to_csv(

    "AI_RDSS_Final_Report.csv",

    index=False

)


# Excel

final_report_df.to_excel(

    "AI_RDSS_Final_Report.xlsx",

    index=False

)


print("✅ Reports Generated")

print("AI_RDSS_Final_Report.csv")

print("AI_RDSS_Final_Report.xlsx")

import pandas as pd

dashboard = pd.DataFrame([
    {
        "Rank": i + 1,
        "Candidate": candidate["Candidate_Name"],
        "Skill Score": candidate["Skill_Score"],
        "Experience Score": candidate["Experience_Score"],
        "Education Score": candidate["Education_Score"],
        "Final Score": candidate["Final_Score"],
        "Decision": candidate["Decision"]
    }
    for i, candidate in enumerate(ranked_candidates)
])

print("="*90)
print("AI RECRUITMENT FINAL DASHBOARD")
print("="*90)

display(dashboard)

dashboard.to_csv(
    "Recruitment_Report.csv",
    index=False
)

print("✅ Recruitment_Report.csv saved successfully")

dashboard.to_excel(
    "Recruitment_Report.xlsx",
    index=False
)

print("✅ Recruitment_Report.xlsx saved successfully")

print("="*100)
print("DETAILED CANDIDATE REPORT")
print("="*100)

for i, candidate in enumerate(ranked_candidates, start=1):

    print("\n")
    print("="*80)

    print(f"Rank               : {i}")
    print(f"Candidate          : {candidate['Candidate_Name']}")
    print(f"Final Score        : {candidate['Final_Score']}")
    print(f"Decision           : {candidate['Decision']}")

    print("\nMatched Skills")
    print(candidate["Matched_Skills"])

    print("\nMissing Skills")
    print(candidate["Missing_Skills"])

    print("="*80)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(
    dashboard["Candidate"],
    dashboard["Final Score"]
)

plt.title("Candidate Final Scores")
plt.xlabel("Candidates")
plt.ylabel("Score")

plt.tight_layout()
plt.show()

dashboard["Decision"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(6,6)
)

plt.ylabel("")
plt.title("Recruitment Decision Distribution")
plt.show()

import os

print(os.listdir())

import os

for file in os.listdir():
    if file.endswith(".png"):
        print(file)

!pip install reportlab

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
import os

def generate_candidate_report(candidate, explanation, recommendation):

    styles = getSampleStyleSheet()

    filename = (
        candidate["Candidate_Name"]
        .replace(" ", "_")
        + "_AI_Report.pdf"
    )

    doc = SimpleDocTemplate(filename)

    story = []

    story.append(
        Paragraph("<b>AI Recruitment System Report</b>", styles["Title"])
    )

    story.append(Spacer(1,0.3*inch))

    story.append(
        Paragraph(
            f"<b>Candidate :</b> {candidate['Candidate_Name']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Final Score :</b> {candidate['Final_Score']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Decision :</b> {candidate['Decision']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Recommendation :</b> {recommendation}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1,0.2*inch))

    story.append(
        Paragraph("<b>Matched Skills</b>", styles["Heading2"])
    )

    for skill in candidate["Matched_Skills"]:
        story.append(
            Paragraph(f"• {skill}", styles["Normal"])
        )

    story.append(Spacer(1,0.2*inch))

    story.append(
        Paragraph("<b>Missing Skills</b>", styles["Heading2"])
    )

    for skill in candidate["Missing_Skills"]:
        story.append(
            Paragraph(f"• {skill}", styles["Normal"])
        )

    story.append(Spacer(1,0.2*inch))

    story.append(
        Paragraph("<b>AI Explanation</b>", styles["Heading2"])
    )

    for line in explanation:
        story.append(
            Paragraph(f"• {line}", styles["Normal"])
        )

    story.append(Spacer(1,0.3*inch))

    if os.path.exists("SHAP_Summary.png"):

        story.append(
            Paragraph("<b>SHAP Explainability</b>", styles["Heading2"])
        )

        story.append(
            Image(
                "SHAP_Summary.png",
                width=6*inch,
                height=4*inch
            )
        )

    doc.build(story)

    print("✅ Report Generated:", filename)

for candidate in ranked_candidates:

    explanation, recommendation = generate_candidate_explanation(candidate)

    generate_candidate_report(
        candidate,
        explanation,
        recommendation
    )

import os

for file in os.listdir():
    if file.endswith(".pdf"):
        print(file)

